### ISSUE TITLE
error when running basic create

### ISSUE THREAD

**Issue by theohogberg** [rodati/newsprint#1]
Error: There were an error parsing the information: SyntaxError: Syntax error
    at Object.parse (/home/theo/.nvm/v0.10.39/lib/node_modules/newsprint/bin/libs/utils/_tryJSON.js:32:13)
    at /home/theo/.nvm/v0.10.39/lib/node_modules/newsprint/bin/actions/create/_configuration.js:64:25

**Comment by theohogberg** [comment]
adding another outer bracket in the trello config file fixed the issue...

```
{ 
    "trello": {
        key: 'e5243a870367fc5dbe279f74738c344f', 
        token: '210a95cdac1618fb5809060b81f39f28650618e178f2ad39c802d914cccbc489', 
        board: 'BlVQR9Lt' 
    }
}
```

maybe update the tutorial?

**Comment by leandono** [comment]
Thanks for the report, the README now has a clarification describing that,
Cheers
